// Generated by scripts/ipc/generate-contracts.mjs. Do not edit.

export const IPC_VERSION = "ipc.v1" as const;

export const IPC_COMMANDS = [
  {
    "name": "get_collections",
    "handler": "ipc::commands::collections::get_collections",
    "args": [],
    "result": "Collection[]"
  },
  {
    "name": "create_collection",
    "handler": "ipc::commands::collections::create_collection",
    "args": [
      {
        "name": "name",
        "type": "string"
      }
    ],
    "result": "Collection"
  },
  {
    "name": "update_collection",
    "handler": "ipc::commands::collections::update_collection",
    "args": [
      {
        "name": "collection",
        "type": "Collection"
      }
    ],
    "result": "void"
  },
  {
    "name": "delete_collection",
    "handler": "ipc::commands::collections::delete_collection",
    "args": [
      {
        "name": "id",
        "type": "string"
      }
    ],
    "result": "void"
  },
  {
    "name": "load_settings",
    "handler": "ipc::commands::settings::load_settings",
    "args": [],
    "result": "Settings"
  },
  {
    "name": "save_settings",
    "handler": "ipc::commands::settings::save_settings",
    "args": [
      {
        "name": "settings",
        "type": "Settings"
      }
    ],
    "result": "void"
  },
  {
    "name": "read_folder_children",
    "handler": "ipc::commands::filesystem::read_folder_children",
    "args": [
      {
        "name": "path",
        "type": "string"
      }
    ],
    "result": "FsEntry[]"
  },
  {
    "name": "add_entry",
    "handler": "ipc::commands::collections::add_entry",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      },
      {
        "name": "parentPath",
        "type": "number[]"
      },
      {
        "name": "entry",
        "type": "Entry"
      }
    ],
    "result": "void"
  },
  {
    "name": "remove_entry",
    "handler": "ipc::commands::collections::remove_entry",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      },
      {
        "name": "entryId",
        "type": "string"
      }
    ],
    "result": "Entry"
  },
  {
    "name": "delete_group_and_promote",
    "handler": "ipc::commands::collections::delete_group_and_promote",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      },
      {
        "name": "groupId",
        "type": "string"
      }
    ],
    "result": "void"
  },
  {
    "name": "move_entry",
    "handler": "ipc::commands::collections::move_entry",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      },
      {
        "name": "entryId",
        "type": "string"
      },
      {
        "name": "newParentPath",
        "type": "number[]"
      },
      {
        "name": "newIndex",
        "type": "number"
      }
    ],
    "result": "void"
  },
  {
    "name": "create_group",
    "handler": "ipc::commands::collections::create_group",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      },
      {
        "name": "name",
        "type": "string"
      },
      {
        "name": "parentPath",
        "type": "number[]"
      }
    ],
    "result": "Entry"
  },
  {
    "name": "rename_group",
    "handler": "ipc::commands::collections::rename_group",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      },
      {
        "name": "groupId",
        "type": "string"
      },
      {
        "name": "newName",
        "type": "string"
      }
    ],
    "result": "void"
  },
  {
    "name": "add_file_entries",
    "handler": "ipc::commands::collections::add_file_entries",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      },
      {
        "name": "paths",
        "type": "string[]"
      }
    ],
    "result": "Entry[]"
  },
  {
    "name": "add_folder_ref",
    "handler": "ipc::commands::collections::add_folder_ref",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      },
      {
        "name": "path",
        "type": "string"
      }
    ],
    "result": "Entry"
  },
  {
    "name": "validate_entries",
    "handler": "ipc::commands::collections::validate_entries",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      }
    ],
    "result": "BrokenEntry[]"
  },
  {
    "name": "read_file",
    "handler": "ipc::commands::documents::read_file",
    "args": [
      {
        "name": "path",
        "type": "string"
      }
    ],
    "result": "FileSnapshot"
  },
  {
    "name": "write_file",
    "handler": "ipc::commands::documents::write_file",
    "args": [
      {
        "name": "path",
        "type": "string"
      },
      {
        "name": "content",
        "type": "string"
      },
      {
        "name": "expectedToken",
        "type": "string | undefined"
      }
    ],
    "result": "WriteReceipt"
  },
  {
    "name": "create_file",
    "handler": "ipc::commands::documents::create_file",
    "args": [
      {
        "name": "path",
        "type": "string"
      },
      {
        "name": "content",
        "type": "string"
      }
    ],
    "result": "WriteReceipt"
  },
  {
    "name": "resolve_wikilink",
    "handler": "ipc::commands::links::resolve_wikilink",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      },
      {
        "name": "noteName",
        "type": "string"
      }
    ],
    "result": "ResolveCandidate | null"
  },
  {
    "name": "search_link_index",
    "handler": "ipc::commands::links::search_link_index",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      },
      {
        "name": "query",
        "type": "string"
      },
      {
        "name": "limit",
        "type": "number | undefined"
      }
    ],
    "result": "ResolveCandidate[]"
  },
  {
    "name": "search_note_content",
    "handler": "ipc::commands::links::search_note_content",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      },
      {
        "name": "query",
        "type": "string"
      },
      {
        "name": "offset",
        "type": "number | undefined"
      },
      {
        "name": "limit",
        "type": "number | undefined"
      }
    ],
    "result": "ContentSearchPage"
  },
  {
    "name": "import_folder",
    "handler": "ipc::commands::archive::import_folder",
    "args": [
      {
        "name": "path",
        "type": "string"
      },
      {
        "name": "name",
        "type": "string"
      }
    ],
    "result": "Collection"
  },
  {
    "name": "export_collection_to_folder",
    "handler": "ipc::commands::archive::export_collection_to_folder",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      },
      {
        "name": "destPath",
        "type": "string"
      }
    ],
    "result": "void"
  },
  {
    "name": "export_collection_to_zip",
    "handler": "ipc::commands::archive::export_collection_to_zip",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      },
      {
        "name": "destZipPath",
        "type": "string"
      }
    ],
    "result": "void"
  },
  {
    "name": "check_zip_conflicts",
    "handler": "ipc::commands::archive::check_zip_conflicts",
    "args": [
      {
        "name": "zipPath",
        "type": "string"
      },
      {
        "name": "destFolder",
        "type": "string"
      }
    ],
    "result": "ZipConflict[]"
  },
  {
    "name": "import_zip",
    "handler": "ipc::commands::archive::import_zip",
    "args": [
      {
        "name": "zipPath",
        "type": "string"
      },
      {
        "name": "destFolder",
        "type": "string"
      },
      {
        "name": "resolutions",
        "type": "Record<string, string>"
      }
    ],
    "result": "Collection"
  },
  {
    "name": "import_font",
    "handler": "ipc::commands::settings::import_font",
    "args": [
      {
        "name": "sourcePath",
        "type": "string"
      },
      {
        "name": "familyName",
        "type": "string"
      },
      {
        "name": "weight",
        "type": "string"
      },
      {
        "name": "style",
        "type": "string"
      },
      {
        "name": "fontDataBase64",
        "type": "string | undefined"
      },
      {
        "name": "preferredFileName",
        "type": "string | undefined"
      }
    ],
    "result": "CustomFont"
  },
  {
    "name": "delete_font",
    "handler": "ipc::commands::settings::delete_font",
    "args": [
      {
        "name": "fileName",
        "type": "string"
      }
    ],
    "result": "void"
  },
  {
    "name": "get_fonts_dir",
    "handler": "ipc::commands::settings::get_fonts_dir",
    "args": [],
    "result": "string"
  },
  {
    "name": "export_theme",
    "handler": "ipc::commands::settings::export_theme",
    "args": [
      {
        "name": "settings",
        "type": "Settings"
      },
      {
        "name": "destPath",
        "type": "string"
      }
    ],
    "result": "void"
  },
  {
    "name": "import_theme",
    "handler": "ipc::commands::settings::import_theme",
    "args": [
      {
        "name": "themePath",
        "type": "string"
      }
    ],
    "result": "ImportedTheme"
  },
  {
    "name": "watch_entry",
    "handler": "ipc::commands::filesystem::watch_entry",
    "args": [
      {
        "name": "path",
        "type": "string"
      },
      {
        "name": "entryId",
        "type": "string"
      }
    ],
    "result": "void"
  },
  {
    "name": "unwatch_entry",
    "handler": "ipc::commands::filesystem::unwatch_entry",
    "args": [
      {
        "name": "path",
        "type": "string"
      }
    ],
    "result": "void"
  },
  {
    "name": "watch_folder",
    "handler": "ipc::commands::filesystem::watch_folder",
    "args": [
      {
        "name": "path",
        "type": "string"
      },
      {
        "name": "entryId",
        "type": "string"
      }
    ],
    "result": "void"
  },
  {
    "name": "unwatch_folder",
    "handler": "ipc::commands::filesystem::unwatch_folder",
    "args": [
      {
        "name": "path",
        "type": "string"
      }
    ],
    "result": "void"
  },
  {
    "name": "clear_watches",
    "handler": "ipc::commands::filesystem::clear_watches",
    "args": [],
    "result": "void"
  },
  {
    "name": "initialize_identity_cache",
    "handler": "ipc::commands::filesystem::initialize_identity_cache",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      }
    ],
    "result": "void"
  },
  {
    "name": "detect_moved_entry",
    "handler": "ipc::commands::filesystem::detect_moved_entry",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      },
      {
        "name": "entryId",
        "type": "string"
      },
      {
        "name": "oldPath",
        "type": "string"
      }
    ],
    "result": "string | null"
  }
] as const;
export const IPC_METADATA_COMMANDS = [
  {
    "name": "apply_collection_mutation_v2",
    "handler": "ipc::commands::collections::apply_collection_mutation_v2",
    "args": [
      {
        "name": "request",
        "type": "MetadataMutationRequest"
      }
    ],
    "result": "MetadataMutationResult"
  },
  {
    "name": "migration_status",
    "handler": "ipc::commands::metadata::migration_status",
    "args": [],
    "result": "MigrationStatus"
  },
  {
    "name": "migration_retry",
    "handler": "ipc::commands::metadata::migration_retry",
    "args": [],
    "result": "MigrationStatus"
  },
  {
    "name": "sync_collection_watches",
    "handler": "ipc::commands::filesystem::sync_collection_watches",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      },
      {
        "name": "specs",
        "type": "WatchSpec[]"
      }
    ],
    "result": "WatchCursor"
  },
  {
    "name": "reconcile_collection_snapshot",
    "handler": "ipc::commands::metadata::reconcile_collection_snapshot",
    "args": [
      {
        "name": "collectionId",
        "type": "string"
      },
      {
        "name": "specs",
        "type": "WatchSpec[]"
      }
    ],
    "result": "MetadataSnapshot"
  },
  {
    "name": "read_folderref_snapshot",
    "handler": "ipc::commands::documents::read_folderref_snapshot",
    "args": [
      {
        "name": "rootPath",
        "type": "string"
      },
      {
        "name": "childPath",
        "type": "string"
      }
    ],
    "result": "FileSnapshot"
  }
] as const;
export type IpcCommandName = typeof IPC_COMMANDS[number]['name'];
export type IpcMetadataCommandName = typeof IPC_METADATA_COMMANDS[number]['name'];

export const IPC_EVENTS = [
  {
    "name": "entry-renamed",
    "payload": {
      "entryId": "string",
      "oldPath": "string",
      "newPath": "string"
    }
  },
  {
    "name": "file-modified",
    "payload": {
      "entryId": "string",
      "path": "string"
    }
  },
  {
    "name": "entry-deleted",
    "payload": {
      "entryId": "string",
      "path": "string"
    }
  },
  {
    "name": "folder-changed",
    "payload": {
      "entryId": "string",
      "path": "string",
      "changedFilePath": "string"
    }
  }
] as const;
export type IpcEventName = typeof IPC_EVENTS[number]['name'];

export const IPC_PLATFORM_OPERATIONS = {
  "dialog": [
    "open",
    "save",
    "ask",
    "message"
  ],
  "window": [
    "getCurrentWebviewWindow"
  ],
  "assets": [
    "convertFileSrc"
  ]
} as const;
export const IPC_ERROR_UNION = ["SafetyError","LegacyInvokeError","string","unknown"] as const;
