// Generated by scripts/feature42/generate-file-capabilities.mjs. Do not edit.

export const FILE_CAPABILITIES_VERSION = "file-capabilities.v1" as const;
export const FILE_CAPABILITIES: readonly { readonly kind: "markdown" | "text-source"; readonly extensions: readonly string[] }[] = [
  {
    "kind": "markdown",
    "extensions": [
      "md",
      "markdown"
    ]
  },
  {
    "kind": "text-source",
    "extensions": [
      "txt",
      "cs",
      "json",
      "toml",
      "yaml",
      "yml",
      "xml",
      "html",
      "htm",
      "js",
      "ts",
      "tsx",
      "jsx",
      "css",
      "scss",
      "sass",
      "less",
      "rs",
      "py",
      "java",
      "c",
      "h",
      "cpp",
      "hpp",
      "go",
      "sh",
      "ps1",
      "sql",
      "ini",
      "cfg",
      "conf",
      "log"
    ]
  }
];
export type FileKind = typeof FILE_CAPABILITIES[number]["kind"];
export const FILE_PICKER_EXTENSIONS: readonly string[] = FILE_CAPABILITIES.flatMap((capability) => capability.extensions);

export function fileExtension(path: string): string {
  const name = path.replace(/\\/g, "/").split("/").pop() ?? "";
  const dot = name.lastIndexOf(".");
  return dot > 0 ? name.slice(dot + 1).toLowerCase() : "";
}

export function classifyFilePath(path: string): FileKind | null {
  const extension = fileExtension(path);
  for (const capability of FILE_CAPABILITIES) if (capability.extensions.includes(extension)) return capability.kind;
  return null;
}

export function isSupportedFilePath(path: string): boolean { return classifyFilePath(path) !== null; }
export function isMarkdownPath(path: string): boolean { return classifyFilePath(path) === "markdown"; }
