// Generated by scripts/ipc/generate-contracts.mjs. Do not edit.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CommandMetadata {
    pub name: &'static str,
    pub handler: &'static str,
}

pub const IPC_VERSION: &str = "ipc.v1";
pub const IPC_COMMANDS: &[CommandMetadata] = &[
    CommandMetadata {
        name: "get_collections",
        handler: "ipc::commands::collections::get_collections",
    },
    CommandMetadata {
        name: "create_collection",
        handler: "ipc::commands::collections::create_collection",
    },
    CommandMetadata {
        name: "update_collection",
        handler: "ipc::commands::collections::update_collection",
    },
    CommandMetadata {
        name: "delete_collection",
        handler: "ipc::commands::collections::delete_collection",
    },
    CommandMetadata {
        name: "load_settings",
        handler: "ipc::commands::settings::load_settings",
    },
    CommandMetadata {
        name: "save_settings",
        handler: "ipc::commands::settings::save_settings",
    },
    CommandMetadata {
        name: "read_folder_children",
        handler: "ipc::commands::filesystem::read_folder_children",
    },
    CommandMetadata {
        name: "add_entry",
        handler: "ipc::commands::collections::add_entry",
    },
    CommandMetadata {
        name: "remove_entry",
        handler: "ipc::commands::collections::remove_entry",
    },
    CommandMetadata {
        name: "delete_group_and_promote",
        handler: "ipc::commands::collections::delete_group_and_promote",
    },
    CommandMetadata {
        name: "move_entry",
        handler: "ipc::commands::collections::move_entry",
    },
    CommandMetadata {
        name: "create_group",
        handler: "ipc::commands::collections::create_group",
    },
    CommandMetadata {
        name: "rename_group",
        handler: "ipc::commands::collections::rename_group",
    },
    CommandMetadata {
        name: "add_file_entries",
        handler: "ipc::commands::collections::add_file_entries",
    },
    CommandMetadata {
        name: "add_folder_ref",
        handler: "ipc::commands::collections::add_folder_ref",
    },
    CommandMetadata {
        name: "validate_entries",
        handler: "ipc::commands::collections::validate_entries",
    },
    CommandMetadata {
        name: "read_file",
        handler: "ipc::commands::documents::read_file",
    },
    CommandMetadata {
        name: "write_file",
        handler: "ipc::commands::documents::write_file",
    },
    CommandMetadata {
        name: "create_file",
        handler: "ipc::commands::documents::create_file",
    },
    CommandMetadata {
        name: "resolve_wikilink",
        handler: "ipc::commands::links::resolve_wikilink",
    },
    CommandMetadata {
        name: "search_link_index",
        handler: "ipc::commands::links::search_link_index",
    },
    CommandMetadata {
        name: "search_note_content",
        handler: "ipc::commands::links::search_note_content",
    },
    CommandMetadata {
        name: "import_folder",
        handler: "ipc::commands::archive::import_folder",
    },
    CommandMetadata {
        name: "export_collection_to_folder",
        handler: "ipc::commands::archive::export_collection_to_folder",
    },
    CommandMetadata {
        name: "export_collection_to_zip",
        handler: "ipc::commands::archive::export_collection_to_zip",
    },
    CommandMetadata {
        name: "check_zip_conflicts",
        handler: "ipc::commands::archive::check_zip_conflicts",
    },
    CommandMetadata {
        name: "import_zip",
        handler: "ipc::commands::archive::import_zip",
    },
    CommandMetadata {
        name: "import_font",
        handler: "ipc::commands::settings::import_font",
    },
    CommandMetadata {
        name: "delete_font",
        handler: "ipc::commands::settings::delete_font",
    },
    CommandMetadata {
        name: "get_fonts_dir",
        handler: "ipc::commands::settings::get_fonts_dir",
    },
    CommandMetadata {
        name: "export_theme",
        handler: "ipc::commands::settings::export_theme",
    },
    CommandMetadata {
        name: "import_theme",
        handler: "ipc::commands::settings::import_theme",
    },
    CommandMetadata {
        name: "watch_entry",
        handler: "ipc::commands::filesystem::watch_entry",
    },
    CommandMetadata {
        name: "unwatch_entry",
        handler: "ipc::commands::filesystem::unwatch_entry",
    },
    CommandMetadata {
        name: "watch_folder",
        handler: "ipc::commands::filesystem::watch_folder",
    },
    CommandMetadata {
        name: "unwatch_folder",
        handler: "ipc::commands::filesystem::unwatch_folder",
    },
    CommandMetadata {
        name: "clear_watches",
        handler: "ipc::commands::filesystem::clear_watches",
    },
    CommandMetadata {
        name: "initialize_identity_cache",
        handler: "ipc::commands::filesystem::initialize_identity_cache",
    },
    CommandMetadata {
        name: "detect_moved_entry",
        handler: "ipc::commands::filesystem::detect_moved_entry",
    },
];
pub const IPC_COMMAND_COUNT: usize = 39;
pub const IPC_METADATA_COMMANDS: &[CommandMetadata] = &[
    CommandMetadata {
        name: "apply_collection_mutation_v2",
        handler: "ipc::commands::collections::apply_collection_mutation_v2",
    },
    CommandMetadata {
        name: "migration_status",
        handler: "ipc::commands::metadata::migration_status",
    },
    CommandMetadata {
        name: "migration_retry",
        handler: "ipc::commands::metadata::migration_retry",
    },
    CommandMetadata {
        name: "sync_collection_watches",
        handler: "ipc::commands::filesystem::sync_collection_watches",
    },
    CommandMetadata {
        name: "reconcile_collection_snapshot",
        handler: "ipc::commands::metadata::reconcile_collection_snapshot",
    },
    CommandMetadata {
        name: "read_folderref_snapshot",
        handler: "ipc::commands::documents::read_folderref_snapshot",
    },
];

#[macro_export]
macro_rules! generated_ipc_handler {
    () => {
        tauri::generate_handler![
            ipc::commands::collections::get_collections,
            ipc::commands::collections::create_collection,
            ipc::commands::collections::update_collection,
            ipc::commands::collections::delete_collection,
            ipc::commands::settings::load_settings,
            ipc::commands::settings::save_settings,
            ipc::commands::filesystem::read_folder_children,
            ipc::commands::collections::add_entry,
            ipc::commands::collections::remove_entry,
            ipc::commands::collections::delete_group_and_promote,
            ipc::commands::collections::move_entry,
            ipc::commands::collections::create_group,
            ipc::commands::collections::rename_group,
            ipc::commands::collections::add_file_entries,
            ipc::commands::collections::add_folder_ref,
            ipc::commands::collections::validate_entries,
            ipc::commands::documents::read_file,
            ipc::commands::documents::write_file,
            ipc::commands::documents::create_file,
            ipc::commands::links::resolve_wikilink,
            ipc::commands::links::search_link_index,
            ipc::commands::links::search_note_content,
            ipc::commands::archive::import_folder,
            ipc::commands::archive::export_collection_to_folder,
            ipc::commands::archive::export_collection_to_zip,
            ipc::commands::archive::check_zip_conflicts,
            ipc::commands::archive::import_zip,
            ipc::commands::settings::import_font,
            ipc::commands::settings::delete_font,
            ipc::commands::settings::get_fonts_dir,
            ipc::commands::settings::export_theme,
            ipc::commands::settings::import_theme,
            ipc::commands::filesystem::watch_entry,
            ipc::commands::filesystem::unwatch_entry,
            ipc::commands::filesystem::watch_folder,
            ipc::commands::filesystem::unwatch_folder,
            ipc::commands::filesystem::clear_watches,
            ipc::commands::filesystem::initialize_identity_cache,
            ipc::commands::filesystem::detect_moved_entry,
            ipc::commands::collections::apply_collection_mutation_v2,
            ipc::commands::metadata::migration_status,
            ipc::commands::metadata::migration_retry,
            ipc::commands::filesystem::sync_collection_watches,
            ipc::commands::metadata::reconcile_collection_snapshot,
            ipc::commands::documents::read_folderref_snapshot,
        ]
    };
}
