// Generated by scripts/feature42/generate-file-capabilities.mjs. Do not edit.

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum FileKind {
    Markdown,
    TextSource,
}

pub const FILE_CAPABILITIES_VERSION: &str = "file-capabilities.v1";
pub const FILE_PICKER_EXTENSIONS: &[&str] = &[
    "md", "markdown", "txt", "cs", "json", "toml", "yaml", "yml", "xml", "html", "htm", "js", "ts",
    "tsx", "jsx", "css", "scss", "sass", "less", "rs", "py", "java", "c", "h", "cpp", "hpp", "go",
    "sh", "ps1", "sql", "ini", "cfg", "conf", "log",
];

pub fn classify_extension(extension: &str) -> Option<FileKind> {
    match extension.to_ascii_lowercase().as_str() {
        "md" => Some(FileKind::Markdown),
        "markdown" => Some(FileKind::Markdown),
        "txt" => Some(FileKind::TextSource),
        "cs" => Some(FileKind::TextSource),
        "json" => Some(FileKind::TextSource),
        "toml" => Some(FileKind::TextSource),
        "yaml" => Some(FileKind::TextSource),
        "yml" => Some(FileKind::TextSource),
        "xml" => Some(FileKind::TextSource),
        "html" => Some(FileKind::TextSource),
        "htm" => Some(FileKind::TextSource),
        "js" => Some(FileKind::TextSource),
        "ts" => Some(FileKind::TextSource),
        "tsx" => Some(FileKind::TextSource),
        "jsx" => Some(FileKind::TextSource),
        "css" => Some(FileKind::TextSource),
        "scss" => Some(FileKind::TextSource),
        "sass" => Some(FileKind::TextSource),
        "less" => Some(FileKind::TextSource),
        "rs" => Some(FileKind::TextSource),
        "py" => Some(FileKind::TextSource),
        "java" => Some(FileKind::TextSource),
        "c" => Some(FileKind::TextSource),
        "h" => Some(FileKind::TextSource),
        "cpp" => Some(FileKind::TextSource),
        "hpp" => Some(FileKind::TextSource),
        "go" => Some(FileKind::TextSource),
        "sh" => Some(FileKind::TextSource),
        "ps1" => Some(FileKind::TextSource),
        "sql" => Some(FileKind::TextSource),
        "ini" => Some(FileKind::TextSource),
        "cfg" => Some(FileKind::TextSource),
        "conf" => Some(FileKind::TextSource),
        "log" => Some(FileKind::TextSource),
        _ => None,
    }
}

pub fn classify_path(path: &std::path::Path) -> Option<FileKind> {
    path.extension()
        .and_then(|extension| extension.to_str())
        .and_then(classify_extension)
}
